// File: lib/firebase_options.dart
// This file would typically be generated by the FlutterFire CLI.
// For instructional purposes, here's a placeholder for the Firebase options.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these placeholder values with your actual Firebase configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAHvviY0SVPE3elSwwzjTZS__U8P-fvluU",
    authDomain: "project-akhir-ae382.firebaseapp.com",
    projectId: "project-akhir-ae382",
    storageBucket: "project-akhir-ae382.firebasestorage.app",
    messagingSenderId: "229707096553",
    appId: "1:229707096553:web:e7e7aa5b11dc2e8675eb78",
    measurementId: "G-KHEHEKDBHW"
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyAHvviY0SVPE3elSwwzjTZS__U8P-fvluU",
    authDomain: "project-akhir-ae382.firebaseapp.com",
    projectId: "project-akhir-ae382",
    storageBucket: "project-akhir-ae382.firebasestorage.app",
    messagingSenderId: "229707096553",
    appId: "1:229707096553:web:f575bfcf8b64e83d75eb78",
    measurementId: "G-CGZ7P98LY6",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHvviY0SVPE3elSwwzjTZS__U8P-fvluU',
    appId: '1:229707096553:android:f32b7b4a61561a8d75eb78',
    messagingSenderId: '229707096553',
    projectId: 'project-akhir-ae382',
    storageBucket: 'project-akhir-ae382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHvviY0SVPE3elSwwzjTZS__U8P-fvluU',
    appId: '1:229707096553:ios:ef4d476e1196690c75eb78',
    messagingSenderId: '229707096553',
    projectId: 'project-akhir-ae382',
    storageBucket: 'project-akhir-ae382.firebasestorage.app',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );
}