// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZvc4kTS_xek7VTWRCk7QGLlu6XD_iGTM',
    appId: '1:423817299367:web:5711868151bfed758a2282',
    messagingSenderId: '423817299367',
    projectId: 'rumahku-b349e',
    authDomain: 'rumahku-b349e.firebaseapp.com',
    storageBucket: 'rumahku-b349e.firebasestorage.app',
    measurementId: 'G-YGQT3KQ5DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxlPJ6yKm8PKwvu_NISsLUibQJGUXkXFY',
    appId: '1:423817299367:android:9c1482c80716899f8a2282',
    messagingSenderId: '423817299367',
    projectId: 'rumahku-b349e',
    storageBucket: 'rumahku-b349e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATyUitobqHFgmHKudSlvPLtR2FbDb4f9c',
    appId: '1:423817299367:ios:b0175f2579b237fc8a2282',
    messagingSenderId: '423817299367',
    projectId: 'rumahku-b349e',
    storageBucket: 'rumahku-b349e.firebasestorage.app',
    iosBundleId: 'com.example.rumahku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATyUitobqHFgmHKudSlvPLtR2FbDb4f9c',
    appId: '1:423817299367:ios:b0175f2579b237fc8a2282',
    messagingSenderId: '423817299367',
    projectId: 'rumahku-b349e',
    storageBucket: 'rumahku-b349e.firebasestorage.app',
    iosBundleId: 'com.example.rumahku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZvc4kTS_xek7VTWRCk7QGLlu6XD_iGTM',
    appId: '1:423817299367:web:08acfd4d8a4cc8238a2282',
    messagingSenderId: '423817299367',
    projectId: 'rumahku-b349e',
    authDomain: 'rumahku-b349e.firebaseapp.com',
    storageBucket: 'rumahku-b349e.firebasestorage.app',
    measurementId: 'G-X123WYX7SM',
  );

}